#!/usr/bin/env python3
"""Measure what % of a Dutch text's tokens are covered by course vocab.

Read-only. Stdlib only. This is the measured-comprehensibility
primitive: before giving the learner a text (verhaal, exercise, dialog),
measure how much of it is already-imported course vocabulary instead of
eyeballing it.

Vocabulary source: `<course>/woordenlijst_index.txt` generated by
`python3 scripts/build_vocab_index.py --course <course>` — run that
first if the index is stale. Courses: link | de_opmaat (link_plus is
NOT supported by the index builder; its index file is a stale
pre-rename snapshot).

Method (deliberately simple — know the limits):
  - lowercase word tokens via regex, apostrophes kept ('s, zo'n)
  - every token appearing anywhere in the in-scope index entries counts
    as known (articles and example-sentence words included)
  - a built-in closed-class function-word list (~100 words) is counted
    separately so grammar words don't inflate "vocabulary" coverage

LIMITATIONS (documented, not fixed):
  - No lemmatization: 'kookte' does not match 'koken'; plurals,
    diminutives and inflected adjectives miss. Coverage is therefore a
    LOWER bound wrt lemmas.
  - de_opmaat's index stores whole example sentences, so its known-set
    is much broader than headwords — coverage vs de_opmaat reads HIGH.
  - Separable verbs split in the text ('ik sta ... op') match only if
    both parts occur somewhere in the index.
  - Proper names count as unknown.

Usage:
    python3 vocab_coverage.py TEXTFILE [--course link] [--max-thema N]
                              [--top 20]

--max-thema N restricts the known-set to themas <= N (what the learner
has actually reached). Exit codes: 0 on success, 1 if the index file is
missing or the input has no Dutch tokens.
"""
import argparse
import collections
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
TOKEN_RE = re.compile(r"[a-zà-öø-ÿ]+(?:'[a-zà-öø-ÿ]+)?|'[a-zà-öø-ÿ]+")
THEMA_RE = re.compile(r"thema[ _]?(\d+)")

# Closed-class Dutch function words (articles, pronouns, prepositions,
# conjunctions, auxiliaries, high-frequency adverbs). Not course vocab.
FUNCTION_WORDS = set("""
de het een ik je jij u hij zij ze we wij jullie ze men me mij jou hem
haar ons onze hun mijn jouw uw zijn dit dat deze die er hier daar en of
maar want dus omdat als toen dan wanneer terwijl hoewel dat wie wat
waar hoe waarom welke welk in op aan bij van naar met voor achter
onder boven tussen door over uit tot sinds na zonder tegen per volgens
ben bent is zijn was waren geweest word wordt worden werd werden heb
hebt heeft hebben had hadden gehad kan kun kunt kunnen kon konden zal
zul zult zullen zou zouden wil wilt willen wilde wilden moet moeten
moest moesten mag mogen mocht mochten ga gaat gaan ging gingen gegaan
doe doet doen deed deden gedaan niet geen wel ook nog al niets iets
alles iedereen niemand ja nee te om heel erg zeer zo toch even maar
eens meer minder veel weinig elke ieder alle beide zelf nu
""".split())


def tokenize(text: str):
    return TOKEN_RE.findall(text.lower())


def load_index(course: str, max_thema):
    path = REPO_ROOT / course / "woordenlijst_index.txt"
    if not path.exists():
        sys.exit(f"index not found: {path}\n"
                 f"run: python3 scripts/build_vocab_index.py "
                 f"--course {course}")
    known = set()
    in_scope = True
    n_sections = 0
    for line in path.read_text("utf-8").splitlines():
        if line.startswith("## "):
            m = THEMA_RE.search(line)
            thema = int(m.group(1)) if m else None
            in_scope = (max_thema is None or thema is None
                        or thema <= max_thema)
            n_sections += 1 if in_scope else 0
            continue
        if line.startswith("#") or not line.strip():
            continue
        if in_scope:
            known.update(tokenize(line))
    return known, n_sections, path


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("textfile")
    ap.add_argument("--course", default="link",
                    choices=["link", "de_opmaat"])
    ap.add_argument("--max-thema", type=int, default=None,
                    help="only count vocab from themas <= N as known")
    ap.add_argument("--top", type=int, default=20,
                    help="how many top unknown tokens to list")
    args = ap.parse_args()

    known, n_sections, idx_path = load_index(args.course, args.max_thema)
    text = Path(args.textfile).read_text("utf-8")
    tokens = tokenize(text)
    if not tokens:
        sys.exit("no Dutch tokens found in input")

    covered = [t for t in tokens if t in known]
    func = [t for t in tokens if t not in known and t in FUNCTION_WORDS]
    unknown = [t for t in tokens if t not in known
               and t not in FUNCTION_WORDS]

    n = len(tokens)
    scope = (f"themas <= {args.max_thema}" if args.max_thema
             else "all themas")
    print(f"=== vocab coverage: {Path(args.textfile).name} ===")
    print(f"index: {idx_path} ({scope}, {n_sections} sections, "
          f"{len(known)} known tokens)")
    print(f"tokens: {n} total, {len(set(tokens))} unique")
    print(f"covered by index:      {len(covered):>5} ({len(covered)/n:.1%})")
    print(f"function words (extra):{len(func):>5} ({len(func)/n:.1%})")
    both = len(covered) + len(func)
    print(f"combined 'should read':{both:>5} ({both/n:.1%})")
    print(f"unknown:               {len(unknown):>5} "
          f"({len(unknown)/n:.1%}, {len(set(unknown))} unique)")

    if unknown:
        freq = collections.Counter(unknown).most_common(args.top)
        print(f"\ntop {min(args.top, len(freq))} unknown tokens "
              "(candidates for pre-teaching or replacement):")
        for tok, c in freq:
            print(f"  {tok:<24} x{c}")
    print("\nNOTE: no lemmatization — inflected forms of known words "
          "count as unknown; treat coverage as a lower bound.")


if __name__ == "__main__":
    main()
