#!/usr/bin/env python3
"""
Builds a compact vocabulary index from all woordenlijst Anki files.

Scans link/ and de_opmaat/ for *woordenlijst*_anki.txt files,
extracts the Word column, and writes a grouped index to
link/woordenlijst_index.txt (or de_opmaat/ respectively).

Usage:
    python3 scripts/build_vocab_index.py              # both courses
    python3 scripts/build_vocab_index.py --course link # only Link
"""

import argparse
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

HEADER_PREFIXES = ("#separator", "#html", "#columns", "#tags", "#notetype")


def find_anki_files(course_dir: Path) -> list[Path]:
    """Find all woordenlijst Anki files, sorted by thema/taak."""
    files = sorted(
        course_dir.rglob("*woordenlijst*_anki.txt"),
        key=lambda p: p.as_posix(),
    )
    return files


def extract_tag(filepath: Path) -> str:
    """Extract thema/taak label from the tag column or filename."""
    # Try to parse from filename: woordenlijst_thema5_taak1_anki.txt
    m = re.search(r"thema(\d+)_taak(\d+)", filepath.name)
    if m:
        return f"thema {m.group(1)} · taak {m.group(2)}"

    # Fallback: derive from directory path
    parts = filepath.relative_to(PROJECT_ROOT).parts
    return " / ".join(parts[:-1])


def extract_words(filepath: Path) -> list[str]:
    """Extract the Word column from an Anki TSV file."""
    words = []
    with open(filepath, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # Word is the first tab-separated column
            word = line.split("\t")[0]
            if word:
                words.append(word)
    return words


def build_index(course_dir: Path) -> str:
    """Build the full index text for a course directory."""
    files = find_anki_files(course_dir)
    if not files:
        return ""

    course_name = course_dir.name
    lines = [f"# {course_name.upper()} — woordenlijst index"]
    lines.append(f"# Auto-generated by build_vocab_index.py")
    lines.append(f"# {sum(len(extract_words(f)) for f in files)} words total")
    lines.append("")

    current_thema = None
    for filepath in files:
        label = extract_tag(filepath)
        # Group by thema
        thema_num = re.search(r"thema\s*(\d+)", label)
        thema_key = thema_num.group(1) if thema_num else label

        if thema_key != current_thema:
            if current_thema is not None:
                lines.append("")
            current_thema = thema_key

        words = extract_words(filepath)
        lines.append(f"## {label} ({len(words)} words)")
        lines.append(", ".join(words))

    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Build vocabulary index from woordenlijst Anki files"
    )
    parser.add_argument(
        "--course",
        choices=["link", "de_opmaat", "both"],
        default="both",
        help="Which course to index (default: both)",
    )
    args = parser.parse_args()

    courses = []
    if args.course in ("link", "both"):
        courses.append(PROJECT_ROOT / "link")
    if args.course in ("de_opmaat", "both"):
        courses.append(PROJECT_ROOT / "de_opmaat")

    for course_dir in courses:
        if not course_dir.exists():
            print(f"⏭  {course_dir.name}/ not found, skipping")
            continue

        index_text = build_index(course_dir)
        if not index_text:
            print(f"⏭  No woordenlijst files in {course_dir.name}/")
            continue

        out_path = course_dir / "woordenlijst_index.txt"
        out_path.write_text(index_text, encoding="utf-8")
        print(f"✅ {out_path.relative_to(PROJECT_ROOT)} written")


if __name__ == "__main__":
    main()
